/* MODELAGEM FÍSICA DO BANCO DE DADOS CLIENTE */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO*/

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTES (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDEREÇO VARCHAR(100)

);

/* VERIFICANDO AS TABELAS DO CAMPO*/

SHOW TABLES; /* COMANDO SÓ EXISTE NO MYSQL*/

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTES;

/* FORMAR DE INSERIR DADOS */

/* FORMA 1 */

INSERT INTO CLIENTES VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 2*/

INSERT INTO CLIENTES(NOME,SEXO,ENDEREÇO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - SOMENTE MYSQL */

INSERT INTO CLIENTES VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  


/*SELEÇÃO PROJEÇÃO E JUNÇÃO */

/* PROJEÇÃO DE DADOS EM FORMA DE TABELA*/

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'AMAURI' AS NOME;


SELECT NOME, SEXO, EMAIL FROM CLIENTES;

SELECT NOME AS CLIENTES, SEXO, EMAIL FROM CLIENTES;

SELECT NOME AS CLIENTES, SEXO, EMAIL, NOW() AS DATA_HORA FROM CLIENTES;

/* SELEÇÃO */

SELECT NOME, SEXO FROM CLIENTES
WHERE SEXO = 'M';

SELECT NOME, ENDEREÇO FROM CLIENTES
WHERE SEXO = 'F';

/* CARACTER CORINGA - %*/

SELECT NOME, SEXO FROM CLIENTES
WHERE ENDEREÇO LIKE '%RJ';

/* CONTA TODAS AS ESNTRADAS DO DATABASE */
SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS" FROM CLIENTES;

/* CONTA AS OCORRÊNCIAS DE CADA TIPO EM UM DETERMINADA COLUNA*/
SELECT SEXO, COUNT(*) FROM CLIENTES
GROUP BY SEXO;
