/* MODELAGEM FÍSICA DO BANCO DE DADOS CLIENTE */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO*/

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ENDEREÇO VARCHAR(100),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	CPF INT(11)

);

/* VERIFICANDO AS TABELAS DO CAMPO*/

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;
