CREATE DATABASE PROJETO1;

USE PROJETO1;

CREATE TABLE DONO (
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR (11)
);

CREATE TABLE CARRO (
	ID_CLIENTE INT,
	MARCA VARCHAR(30) NOT NULL,
	COR1 VARCHAR(30) NOT NULL,
	COR2 VARCHAR(30)
);

ALTER TABLE DONO ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE CARRO ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CLIENTE) REFERENCES DONO(IDCLIENTE);
