CREATE DATABASE PROJETO2;

USE PROJETO2;

CREATE TABLE DONO (
	ID_CLIENTE INT,
	NOME VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR (11)
);

CREATE TABLE CARRO (
	IDCARRO INT,
	MARCA VARCHAR(30) NOT NULL
);

CREATE TABLE CORES (
	ID_COR INT,
	COR VARCHAR(30) NOT NULL
);

ALTER TABLE CARRO ADD CONSTRAINT PK_CARRO
PRIMARY KEY (IDCARRO);

ALTER TABLE DONO ADD CONSTRAINT FK_CARRO_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CARRO(IDCARRO);

ALTER TABLE CORES ADD CONSTRAINT FK_CARRO_CORES
FOREIGN KEY (ID_COR) REFERENCES CARRO(IDCARRO);
