CREATE DATABASE COMERCIO;

USE COMERCIO;
/*
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, --FAZ COM QUE A CHAVE PRIMARIA SEJA CONTROLADA PELO PROPRIO BANCO, EVITANDO QUE SEJAM CRIADAS CHAVES IGUAIS
	NOME VARCHAR(30) NOT NULL, -- O REGISTRO NÃO PODE TER ESSE CAMPO NULO
	SEXO ENUM('M','F') NOT NULL,--FIXA O VALOR QUE O CAMPO PODE ASSUMIR, EXCLUSIVO DO MYSQL, EM OUTROS BANCOS É REALIZADO UMA CONSTRAINT DE CHECK
	EMAIL VARCHAR(50) UNIQUE, --VARIAVEL QUE NÃO PODE SE REPETIR ENTRE OS REGISTROS
	CPF VARCHAR(15) UNIQUE
);
*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR (2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* A CHAVE EXTRANGEIRA ACIMA FICA UNIQUE, PARA IMPEDIR QUE UMA MESMA PESSOA TENHA VÁRIOS ENDEREÇOS, O MESMO NÃO É VERDADE PARA TELEFONE
POIS UMA PESSOA PODE TER VÁRIO TELEFONES

*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/*ENDEREÇO - OBRIGATORIO
CADASTRO DE SOMENTE UM

TELEFONE - NÃO OBRIGATORIO
CADASTRO DE MAIS DE UM (OPCIONAL)

CHAVE ESTRANGEIRA - FOREIGN KEY - FK

 */
 
 /* PASSAR NULL COMO CHAVE PRIMARIA SO OCORRE NO MYSQL */
 
INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M','JOAO@IG.COM','71274127');
INSERT INTO CLIENTE VALUES(NULL, 'BRUNA', 'F','BRUM@IG.COM','12651361');
INSERT INTO CLIENTE VALUES(NULL, 'PEDRO', 'M','PEDRO@IG.COM','51251231');
INSERT INTO CLIENTE VALUES(NULL, 'FABIO', 'M','FABIO@IG.COM','51251312');
INSERT INTO CLIENTE VALUES(NULL, 'ESTELA', 'F','ESTELA@IG.COM','52131251');
INSERT INTO CLIENTE VALUES(NULL, 'TATI', 'F','TATI@IG.COM','632412312');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA', 'F',NULL,'93592342');

INSERT INTO ENDERECO VALUES(NULL, 'RUA 3', 'TAGUATINGA', 'BRASILIA', 'DF',1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA 5 NORTE', 'AGUAS CLARAS', 'BRASILIA', 'DF',2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA 6', 'ASA NORTE', 'BRASILIA', 'DF',3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRES VARGAS', 'JARDINS', 'SAO PAULO', 'SP',4);
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ',5);
INSERT INTO ENDERECO VALUES(NULL, 'RUA 7 SUL', 'SUDOESTE', 'BRASILIA', 'DF',6);
INSERT INTO ENDERECO VALUES(NULL, 'RUA 9', 'GAMA', 'BRASILIA', 'DF',7);

INSERT INTO TELEFONE VALUES(NULL, 'RES', '983721231', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '983745211', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '725123123', 3);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '521412325', 2);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '125123215', 4);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '983721231', 5);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '125121231', 5);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '613215215', 7);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '512453123', 5);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '541231253', 6);


SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO, NUMERO 
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/* COM PONTEIRAMENTO */
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

